### PR TITLE
Implement a while loop for when queue aren't empty

### PR DESCRIPTION
**Pull request by thomasyu888**
You may have to run the submissions that come in the fanout queue in succession, but those submissions should run really fast.

#9

### CODE REVIEW

**Comment by Simon-Harris-IBM** [comment]
Thanks @thomasyu888 
Not sure I understand you last comment though ? Could you expand please.....

**Comment by thomasyu888** [comment]
Which comment? You can specify submissions to run concurrently via the orchestrator. It may be safer to run through one submission at a time with the fanout queue so that submissions aren't submitted to the same open queue by chance

**Comment by Simon-Harris-IBM** [comment]
OK, so I think what you're saying is that for the main fanout queue, then we should set MAX_CONCURRENT_WORKFLOWS=1  in the .env file of the orchestrator ???

**Comment by thomasyu888** [comment]
Yup! Sorry for the confusion

**Comment by Simon-Harris-IBM** [comment]
No worries - I'll test this code out later today

**Comment by Simon-Harris-IBM** [comment]
This will require quite a bit of testing and I don't have time before I have to leave for the weekend. I'll leave this one up to @mummert-ibm to pull and test :-)

**Review by mummert-ibm — APPROVED** [review]

**Pull request merged**
