### PR TITLE
Use the right submitterSynid and adminSynId 

### PR DESCRIPTION
**Pull request by thomasyu888**
* created tool that added the admin synid annotation to the fanout queue submission
* get_submission_docker obtained the `adminUploadSynId` and `submitterUploadSynId`

### CODE REVIEW

**Comment by thomasyu888** [comment]
Merge this after #17

**Comment by thomasyu888** [comment]
#18 , #11

**Comment by Simon-Harris-IBM** [comment]
I merged #17, then this PR.
 - the submitter now received 3 emails - start/finish on the fan-out Q and the scoring email
 - I still receive start/complete on the backend queue

Is the idea to control these emails by setting the following in the .env file:
"Set this in your .env

SUBMITTER_NOTIFICATION_MASK - controls for which events notifications are sent to the submitter. The integer value is a union of these masks:

1: send message when job has started;
2: send message when job has completed;
4: send message when job has failed;
8: send message when job has been stopped by user;
16: send message when job has timed out;
Also people won't be notified of Processing started on main q #. You get emails because you are the admin user submitting."

This will be difficult to implement at the moment because we have "fanoutQ & backendQ2" using the same orchestrator and "express-lane and backendQ1" using another orchestrator. Once we have more machines, the aim is to to put "fanoutQ & express-lane" under 1 orchestrator and then have one orchestrator per backendQ.
For "fanoutQ & express-lane" we should be able to keep the current settings. For all backendQ's we can set the above so it doesn't send any emails. Make sense ?

**Comment by thomasyu888** [comment]
That's right. You will control the orchestrator sent emails through your .env file, but that's why I had #17 because that email sends them notification emails.


That is why you will want to put fanout queue with express lane so that those have the same email settings and then the main queues i think there may even be a setting to turn off notifications all together?

**Pull request merged**
